#see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#deployment-v1-apps
apiVersion: apps/v1 # Api version for below object.
kind: Deployment # Type of object
metadata:
  name: webappdemo-deployment # Name of your Deployment
spec:
  selector:
    matchLabels:
      app: webappdemo
  replicas: 5 # Desired number of pods for the replica set
  template:
    metadata:
      labels:
        app: webappdemo
    spec:
      containers:
      - name: webappdemo
        image: nginx
        ports:
        - containerPort: 80